Script started on 2016年03月13日 (週日) 21時50分03秒
]0;F74041072@2015cpp: ~/lab1F74041072@2015cpp:~/lab1$ git clone https://github.com/super24618045/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwd[7Pexitgit config -l[1P-l[7Pls -acd lab1ls[Kmv lab1.script lab1ls[Kcd lab1[2Pls -agit config-l -lexit[Kwhoami; pwdgit config -llone https://github.com/super24618045/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K./hw1
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;F74041072@2015cpp: ~/lab1F74041072@2015cpp:~/lab1$ exit

Script done on 2016年03月13日 (週日) 21時50分38秒
